### ISSUE TITLE
The strong loading of the network block causes the server to freeze seriously

### ISSUE THREAD

**Issue by HPflower** [Sefiraat/Networks#102]
Is it possible to generate a config file to choose whether to turn off strong loading of network blocks? On our servers, chunks where there are network blocks are loaded automatically and keep loading regardless of whether or not a player is online on the server, causing a significant lag on the server. I know that turning off strong loading of the network system might disable tools like Remote Control, but if it improves the server's tps, I think it's worth giving up on these
![A P{)V_(YFB0%VCNA_0`0IJ](https://user-images.githubusercontent.com/102914382/188561221-2ce0a059-8c5a-4e31-a42f-043f3a10b1da.jpg)

**Comment by Sefiraat** [comment]
Slimefun decides when a block ticks or not and is decided on if the given chunk is loaded by other means. Nothing in Networks will load chunks by itself nor keep them loaded beyond the normal unloading behaviour. 

Additionally networks doesn’t run in the main thread and shouldn’t cause you issues (vanilla grabbers and pushers are an exception to this but as they aren’t in your timings I’ll ignore that for now). 

If you still believe it’s networks causing the issues, please can you provide a 5 min, all thread, spark report that covers a period of freezing.

Thanks :)

**Comment by HPflower** [comment]
After checking, we found that strong loading is not a network-affiliated issue, but a feature left over after another affiliated plugin was removed. The lag of the server has been wonderfully fixed after the feature was removed, thanks for the prompt reply

**Comment by Sefiraat** [comment]
Good to hear!
