### ISSUE TITLE
Pusher cannot push into Vaporizer

### ISSUE THREAD

**Issue by TecnoRed20** [Sefiraat/Networks#103]
Hello, I was trying to automate the generation of sulfate, for this I used a machine (Vaporizer) from the ExtraTools addons (https://github.com/Sfiguz7/ExtraTools), because apparently the pushers are not capable of pushing the lava cubes inside of the vaporizer

I am a user of the server, I think that the version of Networks that is used is the one in which the Capacitor4 were published.
SF version 1.18.2 - Dev 1027

**Comment by Sefiraat** [comment]
Is cargo capable of pushing items into it?

**Comment by komodowaran** [comment]
On 1.19 pushers can push lava buckets correctly in to Vaporizer's
So it might be only a 1.18 problem. 
Or it might be that the Lavabuckets are stored in a storage unit from infinity expansion  (they don't work correctly for unstackable lavabuckets) and would work if the lava buckets were in a quantum storage unit
