### ISSUE TITLE
Wildchests and networks ( slimefun ) bug glitch

### ISSUE THREAD

**Issue by SrMonsterYT** [Sefiraat/Networks#107]
using Networks VANILLA GRABBER and Networks VANILLA PUSHER from the slimefun addon (Networks), you can duplicate items infinitely, the video shows everything.

how to do the bug is in the link: https://youtu.be/KJ653aNp_oY

server version and addons: https://prnt.sc/GW2greh9b8WM

**Comment by SrMonsterYT** [comment]
> 

thank you for answering me, and saying that compatibility will be added, thank you very much.

**Comment by SrMonsterYT** [comment]
here is the API for compatibility, I looked it up so it helps you not to have to search.
https://bg-software.com/wildchests/api/

**Comment by SrMonsterYT** [comment]
so any news?

**Comment by Sefiraat** [comment]
? the most up to date news is above?

**Comment by SrMonsterYT** [comment]
> ? the most up to date news is above?

yes

**Comment by Sefiraat** [comment]
There would be a post, link or anything similar when there is an update. Please remember this is an optional enhancement/compatibility and not an urgent bug fix. I also do not work for you so it would be great if you followed my advice above and await further information.

**Comment by RelativoBR** [comment]
@Sefiraat I did some local tests and this change managed to ignore the Bau of this API wildchests:

[ https://github.com/Sefiraat/Networks/pull/122](https://github.com/Sefiraat/Networks/pull/122)

**Comment by SrMonsterYT** [comment]
it seems that after updating slimefun to Slimefun DEV - 1049 (git 735e4cc3) the bug is back only in VANILLA GRABBER

video: https://youtu.be/C2cVnxSDGqs

1° image: https://prnt.sc/dfobS7FB3zme
2° image: https://prnt.sc/0rwuNUd1LPfc
3° image: https://prnt.sc/BlnVhNXnere0  ( server version and slimefun addons )

no error console

**Comment by SrMonsterYT** [comment]
?
