### ISSUE TITLE
[Bug] Network vanilla grabber has the wrong name in its lore

### ISSUE THREAD

**Issue by Katakalysm** [Sefiraat/Networks#113]
![image](https://user-images.githubusercontent.com/105556520/198752149-d8f0b552-609c-440b-be22-8fa9d865b7f1.png)

A relatively harmless bug to be sure, and it's only in the first line.

**Comment by JustAHuman-xD** [comment]
What is incorrect?

**Comment by Sefiraat** [comment]
> What is incorrect?

It says pusher :). It's fixed and will be pushed in the next build.

**Comment by JustAHuman-xD** [comment]
Ah I'm blind lol
