### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by NgTuanAnhDev** [Sefiraat/Networks#154]
I used sf timings and found out that networks are causing a lot of lag on my server
https://spark.lucko.me/F4VJEl0b1U?hl=42369
[14:27:51 INFO]: Slimefun 4> Vui lòng đợi một chút... Kết quả chuẩn bị đến!
[14:27:56 INFO]: 
[14:27:56 INFO]: ===== Slimefun Lag Profiler =====
[14:27:56 INFO]: Total time: 5094.24ms
[14:27:56 INFO]: Running every: 0.5s (10 ticks)
[14:27:56 INFO]: Performance: :::::::::::::::::::: - Bad (5094%)
[14:27:56 INFO]: 
[14:27:56 INFO]: 34017 blocks
  NTW_GRABBER - 5432x (2672.57ms | avg: 0.49ms)
  NTW_PUSHER - 1514x (1798.68ms | avg: 1.19ms)
  SUPREME_TECH_GENERATOR - 2270x (122.21ms | avg: 0.05ms)
  ENERGY_REGULATOR - 34x (120.85ms | avg: 3.55ms)
  NTW_AUTO_CRAFTER - 63x (114.14ms | avg: 1.81ms)
  SUPREME_BASIC_VENTUS_GENERATOR - 4659x (55.92ms | avg: 0.01ms)
  CARGO_NODE_INPUT - 1002x (33.47ms | avg: 0.03ms)
  NTW_CONTROLLER - 19x (30.35ms | avg: 1.6ms)
  SUPREME_ELECTRIC_CORE_I - 162x (14.94ms | avg: 0.09ms)
  AUTO_ENHANCED_CRAFTING_TABLE - 14x (14.75ms | avg: 1.05ms)
  ETC_MATERIALIZER_3 - 1803x (14.53ms | avg: 0.01ms)
  SUPREME_ELECTRIC_MAGICAL_I - 3x (10.15ms | avg: 3.38ms)
  CARGO_MANAGER - 28x (7.95ms | avg: 0.28ms)
  ELECTRIC_DUST_FABRICATOR - 127x (7.6ms | avg: 0.06ms)
  SINGULARITY_CONSTRUCTOR - 551x (7.51ms | avg: 0.01ms)
  DUST_EXTRACTOR - 130x (6.86ms | avg: 0.05ms)
  NTW_CELL - 8781x (5.05ms | avg: 0ms)
  ETC_MATERIALIZER_1 - 996x (4.18ms | avg: 0ms)
  ELECTRIC_SPAWNER_WITHER_SKELETON - 4x (2.57ms | avg: 0.64ms)
  MINI_FLUFFY_BARREL - 105x (2.52ms | avg: 0.02ms)
+ 163 more...
[14:27:56 INFO]: 159 chunks
  world (-1003,-1330) - 2145 blocks (2838.24ms)
  world (1403,-756) - 680 blocks (397.1ms)
  world (1404,-756) - 894 blocks (328.91ms)
  world (-1003,-1329) - 926 blocks (183.85ms)
  world (-1004,-1330) - 1641 blocks (117.24ms)
  world (-1004,-1328) - 1635 blocks (112.67ms)
  world (-1003,-1328) - 1928 blocks (105.83ms)
  world (1404,-752) - 194 blocks (99.7ms)
  world (-1004,-1329) - 952 blocks (80.87ms)
  world (1404,-757) - 378 blocks (79.13ms)
  world (1405,-756) - 499 blocks (76.45ms)
  world (1404,-755) - 99 blocks (65.88ms)
  world (1510,1235) - 437 blocks (60.92ms)
  world (1026,666) - 1481 blocks (49.59ms)
  world (-942,-958) - 840 blocks (40.04ms)
  world (1509,1235) - 796 blocks (32.42ms)
  world (1025,666) - 2570 blocks (32.37ms)
  world (-943,-958) - 393 blocks (30.4ms)
  world (1023,279) - 221 blocks (28.38ms)
  dimensionalhome (-1,15) - 236 blocks (26.56ms)
+ 139 more...
[14:27:56 INFO]: 25 plugins
  Networks - 19806 blocks (4629.85ms)
  Supreme - 7240 blocks (208.3ms)
  Slimefun - 1834 blocks (172.32ms)
  FluffyMachines - 312 blocks (25.95ms)
  InfinityExpansion - 1509 blocks (24.02ms)
  EMCTech - 2955 blocks (20.56ms)
  ElectricSpawners - 8 blocks (4.52ms)
  DynaTech - 55 blocks (3.34ms)
  FNAmplifications - 28 blocks (1.29ms)
  Galactifun - 6 blocks (1.13ms)
  SlimeFrame - 5 blocks (0.94ms)
  ExtraTools - 26 blocks (0.58ms)
  SlimeTinker - 19 blocks (0.3ms)
  SimpleMaterialGenerators - 22 blocks (0.29ms)
  LiteXpansion - 13 blocks (0.27ms)
+ 10 more...

**Comment by JustAHuman-xD** [comment]
Probably because there are 19 **thousand** networks blocks.

**Comment by JustAHuman-xD** [comment]
Nearly 20

**Comment by Sefiraat** [comment]
As the bulk of the timings actually go into the off-thread it would directly cause lag, but as Human mentioned above, you place 20,000 of anything then you're going to start to have some potential issues.
