### ISSUE TITLE
[suggestion]Add config to disable NTW Quantum storage(item)'s lore to display name of stored item

### ISSUE THREAD

**Issue by m1919810** [Sefiraat/Networks#165]
This display may cause serious consequence while the server add "lore-based RPG plugins" like AttributePlus which  works by reading the lore of player's equipments
players can rename the item ,stored in Qstorage and put it on mainhand/offhand slot to modify their attribute value

**Comment by JustAHuman-xD** [comment]
This sounds like more of a bug on that plugins side

**Comment by JustAHuman-xD** [comment]
Judging purely on name and not nbt is bad practice always

**Comment by Sefiraat** [comment]
Yeah, I'm not sure I would ever want to NOT display the lore of a given item?
