### ISSUE TITLE
Network (Crafting) Grid doesn't show any item when use filter

### ISSUE THREAD

**Issue by BlazeHunterVN1610** [Sefiraat/Networks#172]
When I click on the filter button (name tag) and search for item, nothing show up in the grid inventory. Even if there is only one 1 item in the network and and when i search for it, it doesn't appear in the grid

**Comment by JustAHuman-xD** [comment]
Do you have a plugin that colors chat messages?

**Comment by BlazeHunterVN1610** [comment]
Yes, but even when I turn off the colors chat, the filter still not show the item. Btw, i'm not the server's admin, and the server I played closed 2 months ago, so I can't provide the server log or anything like that

**Comment by Sefiraat** [comment]
It's my fault for not addressing this earlier, but with the server closed and no logs, I can't do anything with this at the mo - really appreciate the report still however :D
