### ISSUE TITLE
[Bug] Dupe item

### ISSUE THREAD

**Issue by balugaq** [Sefiraat/Networks#188]
The video is too big to upload at here. So I will report it with a lot of text.

The main way to dupe item:
Step 1. Destory Network Cell without player interacting and turn the block to air
- At the end, you can see his implementation.
- Now, the network still stores the cell and didn't notice that the Network Cell was broken.
- So we can place the other Network Grid and store items to this "Air Cell".
Step 2. Place a Network Grid at the Air Cell.
- Now, the network notices there's a new Network Machine, and store it.
- But the Air Cell's data didn't cleared.
- So this location will be considered both Network Cell and Network Grid at the same time.
Step 3. Open the Network Grid, you can see the Network Grid is showing it self. It makes duping item.
- ① As for the Network Grid, it will show all the items in the network and it's background glass panes to it's menu.
- ② As for the network, it is a Network Cell. So all the items in the menu of the Network Grid will record.
- Notice ①, the Network Grid will show itself.
- Before Step 3, we can put some items we want to the network, and still follows the step, it can dupe this item.
- Although the item duped has some addition lore, but it's main data still store. We can put a Shulker Box, Infinity Storage or Network Quantum Storage, and the addition text will NOT affect the use. So we duped a complete storage.

A way to implement Step 1:
- Put a dirt on the Network Cell, and put a Magical Essence from ExoticGarden.
- Use bone meal to grow it up, and appeared a leave.
- Use fire to burn down this leave.
- Notice the fire, if the fire spread on the dirt, left-click it. 
- Then you can see the dirt was destoryed, and the Magical Essence grows on the Network Cell.
- Repeat the steps, we can destoy the Network Cell without player interacting.

**Comment by Mae-8** [comment]
The network grid just bugs out and keeps adding empty glass plain over and over again, if you put any items in to the network through the grid, it just takes it, it doesn't exactly work as a dupe

**Comment by balugaq** [comment]
No, you can put some acutal items. and then check the grid quickly. You can see these items duped.

**Comment by balugaq** [comment]
Or.. you can put a Infinity Barrel with items, then take the duped Barrels and put them down.

**Comment by Mae-8** [comment]
Can you just record it, post it on youtube, then copy the link here?

**Comment by balugaq** [comment]
I try my best.. I'm in China so that I have big lag on youtube.

**Comment by Mae-8** [comment]
Alright thanks

**Comment by rakhabilly1** [comment]
i can't recreate this, can u send the vid

**Comment by balugaq** [comment]
Sorry, may I missed a step to reproduce it. And it is the video
https://1drv.ms/v/s!AkG7xmp0rLSobwNWVj22RPbUEUM?e=7AiRPQ

**Comment by balugaq** [comment]
Maybe it fixed on the Chinese version with these prs.
https://github.com/SlimefunGuguProject/Networks/pull/100
https://github.com/SlimefunGuguProject/Networks/pull/104
https://github.com/SlimefunGuguProject/Networks/pull/118

**Comment by balugaq** [comment]
I wonder why the network's version is DEV 1. I just built it to jar by myself.

**Comment by balugaq** [comment]
> Maybe it fixed on the Chinese version with these prs.
It seems that these PRs still haven't had a repairing effect

**Comment by balugaq** [comment]
"Here is a proposed solution to fix issues #188 and #192:

Convert all slots in the Cell to output slots.
Also, convert the receive slot in GreedyBlock to an output slot.
In the registerNode function of NetworkRoot, check the transportable slots of the incoming location for both Cell and GreedyBlock.
If the check passes, it indicates that the block is available. Otherwise, do not add it to the cells or greedyblocks lists.
I would like to submit a pull request for this fix, but I currently have other ongoing work in the project’s branch."

**Comment by balugaq** [comment]
You can refer to https://github.com/balugaq/NetworksExpansion/blob/master/src/main/java/io/github/sefiraat/networks/network/NetworkRoot.java#L124 to https://github.com/balugaq/NetworksExpansion/blob/master/src/main/java/io/github/sefiraat/networks/network/NetworkRoot.java#L149. In some places, `StorageCacheUtils.getMenu` is used, which can be replaced with `BlockStorage.getInventory`. I'm not sure if this works in the official version, but it does work in the Chinese localization version. As for why I haven't submitted a PR, it's because I have many other modifications in these files.

**Comment by balugaq** [comment]
I have tested multiple times, and also involved a large number of professionals to test, but neither issue #188 nor issue #192 could be reproduced. So this is most likely an effective solution.

**Comment by balugaq** [comment]
A possible fix has been found ↑. @Sefiraat

**Comment by lijinhong11** [comment]
There's a fixed version: https://www.mediafire.com/file/al99589iui2m2el/networks_vMODIFIED.jar/file

**Comment by balugaq** [comment]
Fixed
