### ISSUE TITLE
[Bug] Dupe item 2

### ISSUE THREAD

**Issue by balugaq** [Sefiraat/Networks#192]
It's a easier way to dupe items (compare it with #188 )
The first video about duping items was deleted in #188 . Because of this matter, I will only use text to describe it this time. If managers need a video, please message me privately.

[Declaration]
This is a low chance bug.

1. Prepare Network Grid x1, Network Monitor x1, Network Controller x2, Network Cell x1, and Basic Storage from InfinityExpansion x1 with some items in it.

( Here we agree on the following:
* G = Network Grid,
* M = Network Monitor,
* C = Network Controller,
* E = Network Cell,
* S = Basic Storage with cobblestone x1234.
* -- = Just air

2. Facing north, and put these block down

North
↑↑↑↑↑

GM
--E

3. Select the monitor's direction as the south to monitor the Network Cell.
4. Open the Network Grid, until it's GUI refresh.
5. Put down two Network Controllers quickly like this:

GMCC
--E

Then, one of them will drop. And we except this shape. If it's not similar to this, just try again.

GM--C
--E

6. Replace the Network Cell to Basic Storage.

GM--C
--S

7. Place the dropped Network Controller in the middle empty space, and it will drop on of them again. We need this shape:

GMC
--S

8. Then, open the Network Grid, you can see all the GUI in Basic Storage are showing in it.
9. Just replace the cobblestone in the middle GUI to another item we want.
10. Open the GUI, we can see that we duped successfully.

[Declaration again]
This is a low chance bug.

**Comment by balugaq** [comment]
From https://github.com/SlimefunGuguProject/Networks/issues/120
And it may be related to https://github.com/Sefiraat/Networks/issues/188

**Comment by lijinhong11** [comment]
There's a fixed version: https://www.mediafire.com/file/al99589iui2m2el/networks_vMODIFIED.jar/file

**Comment by TakeshiOver** [comment]
@balugaq poderia me passar seu Discord?

**Comment by balugaq** [comment]
Fixed
