### ISSUE TITLE
[BUG] Dupe item 3 (Only Blueprints)

### ISSUE THREAD

**Issue by balugaq** [Sefiraat/Networks#201]
https://github.com/user-attachments/assets/bb81ca14-72e4-450c-b559-699a2b11a781

Seems `CraftingBlueprint` doesn\'t `implements DistinctiveItem`

**Comment by lijinhong11** [comment]
There's a fixed version: https://www.mediafire.com/file/al99589iui2m2el/networks_vMODIFIED.jar/file

**Comment by balugaq** [comment]
Fixed
