### ISSUE TITLE
Networks is using all of my 28GB of RAM in my 1.20 server

### ISSUE THREAD

**Issue by MeowIce** [Sefiraat/Networks#210]
Quick comparison:
WITH Network:
![image](https://github.com/user-attachments/assets/f3876ed4-f6da-4cf2-8408-3303eb645239)
WITHOUT Networks:
![image](https://github.com/user-attachments/assets/8db7e3ed-d07a-4af3-94eb-3afa51dfbc55)
Daily players: 60-80
SF Profiler:
![image](https://github.com/user-attachments/assets/05301a27-0b20-4970-be09-eaf29c0eb08d)
I noticed that Network Cells are so inefficient at saving data, especially with Slimefun items that have lots of data (NBT Tags).
If you need more information to troubleshoot this issue or reduce RAM usage, let me know.
Thanks !

**Comment by Sefiraat** [comment]
You have been told so very many times before, I cannot and will not support your cracked server. I have checked with other servers with networks with similar player bases who do not have this issue. So I will close this issue and will not tell you again, as mentioned in my DM to you, to not come to me or slimefun in general with issues on your cracked server. Please and thank you.

**Comment by MeowIce** [comment]
It's the whole issue with your goddamn addon. What server did you _checked with other servers with networks with similar player bases who do not have this issue_ ? Because they don't have the same gameplay as us and you're trying to hide the inefficiency of how you load and save the data of Networks ?
You said mine is a cracked server then if another cracked server report the bugs, you still say that then ignore the bug report ?
Do you know how much pain you gave for Slimefun server owners ? Buggy DankPacks, Networks The Dupe Addon, CrystamaeHistoria the bedrock breaker,.. If I report those then will you fix them ? Or just ignore as _We don't provide supports for cracked servers_ ?

**Comment by Sefiraat** [comment]
If you dislike it so much, remove the addon? Isn’t that simple enough? Also 3/4 of your utter rant has nothing to do with this one issue which is the one I closed. This ONE issue has not been reported on other servers with similar player bases narrowing it down to just you and I will NOT BE HELPING YOU AS YOURE ON A CRACKED SERVER. kinda simple when you boil it down to the base facts and don’t bring in external arguments to reinforce another. You have been warned so many times that this is the result of you running a cracked server and then asking for help. What did you expect?
