### ISSUE TITLE
Network Grabber Dupe

### ISSUE THREAD

**Issue by SrMonsterYT** [Sefiraat/Networks#212]
I found a player's land where he has several chests with machines and slimefun items, all of them have the name, Grabber and their direction as EAST, NORTH...

In short, all the items came from Grabber

image: https://prnt.sc/VVmLdBHvm2-l

video: https://youtu.be/FkgXRRXXFqk

I don't know how to reproduce it, I know there are players doing it

server and addons version: https://prnt.sc/4by3XlcYNqgv

**Comment by balugaq** [comment]
Similar to #211

**Comment by balugaq** [comment]
theres no place & break block listener in offical version, after #211 step 2, just place the grabber directly.

**Comment by Sefiraat** [comment]
Resolved in latest build
