### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by 12XpresS12** [Sefiraat/Networks#28]
https://pastebin.com/zv8LEjq2

Exception while I shift right click on filter in network grid.

**Comment by Sefiraat** [comment]
I am not able to recreate this despite trying - please can you provide more information or a stream of you doing this?

**Comment by 12XpresS12** [comment]
Nahh, now i cant recreate it. :/ sorry

**Comment by Sefiraat** [comment]
No worries! Let’s hope it’s something I have fixed and we overlapped on versions :). I’ll close this for now and feel free to reopen if you get it again :)
