### ISSUE TITLE
Can bind to other's network grid using network remote

### ISSUE THREAD

**Issue by SideLo98** [Sefiraat/Networks#30]
players are able to bind with anyone's network grid and access their stored items using network remote.

https://streamable.com/7yfffa

**Comment by Sefiraat** [comment]
Can you provide a /sf versions for this and confirm it is still happening at the time you ran the command please as I would have expected this to be resolved in build 19

**Comment by SideLo98** [comment]
sorry for late response, yes it seems to fixed in build 20 not sure about build 19 as I updated to latest and I was on build 16 before so all good now. Thanks
![image](https://user-images.githubusercontent.com/67060780/151300619-0be23d59-ffb8-436f-a701-1dc26e7c1a06.png)

**Comment by Sefiraat** [comment]
Glad to see it was fixed - sorry for the duration in which it was broken :)
