### ISSUE TITLE
Stack Itens

### ISSUE THREAD

**Issue by brasilcraft54** [Sefiraat/Networks#37]
one thing that would be nice instead of him grouping 64 in each slot he could show only 1 item and if you pass the mouse over it would show the amount of items he has, like 9999.

exemple: https://prnt.sc/26nlu3q

equal to this mod  https://www.curseforge.com/minecraft/mc-mods/toms-storage

**Comment by Sefiraat** [comment]
Uh, Networks has this in the form of the Network Grid which says how much of each item, cumulatively between all exposed points, is in the Network? 

Please see [this link](https://sefiraat.gitbook.io/docs/networks/network-nodes/network-grid) if it helps you.

**Comment by brasilcraft54** [comment]
> Uh, Networks has this in the form of the Network Grid which says how much of each item, cumulatively between all exposed points, is in the Network?
> 
> Please see [this link](https://sefiraat.gitbook.io/docs/networks/network-nodes/network-grid) if it helps you.

and how do I store the 1 million items, would I have to have several honey blocks the size of a castle? wouldn't it be easier to have 1 honey block and on the other side a place to add memory and store everything inside the Network Grid instead of having it all inside the commerce blocks? or would each commerce be like the wildchests plugin with an infinite system to store items?

**Comment by Sefiraat** [comment]
That's what a [Network Monitor](https://sefiraat.gitbook.io/docs/networks/network-nodes/network-monitor) is for - it allows you to expose the contents of a [Network Shell](https://sefiraat.gitbook.io/docs/networks/network-nodes/network-memory-shell), which with the correct [memory card](https://sefiraat.gitbook.io/docs/networks/tools/network-memory-card) can hold 2bil~ items or with Infinity Expansion the Infinity Storage which also holds between 4k - 2bil~ items. You have plenty of options

**Comment by brasilcraft54** [comment]
> 

I still do not understand how to put 2kk of items armazenas I would have to put many hive blocks or there is a way to not need to use so many hives, sorry so many questions but I liked it the problem that is difficult to understand how it works.

**Comment by Sefiraat** [comment]
You need to click the links I posted above and read the content - they explain exactly how to do what you want?

You do not need to use Network Cells (hives) at all if you don’t want to. Please read what i sent you
