### ISSUE TITLE
Network Auto Crafter (Withholding)'s will seek to fill their output slot to the maximum stack size irregardless of the recipe output quantity size

### ISSUE THREAD

**Issue by BurningBrimstone** [Sefiraat/Networks#39]
Issue: Network Auto Crafter (Withholding)'s will seek to fill their output slot to the maximum stack size irregardless of the recipe output quantity size.

Example: Creating a Crafting Blueprint for glass panes (6 Glass -> 16 Glass panes) and placing it into a Network Auto Crafter (Withholding) will cause the crafter to always fill the output stack, even if there is more than 48 items in the output slot, meaning that all excess crafted items are voided.

Expected Behavior: The Network Auto Crafter (Withholding) will wait for there to be adequate space for the recipe to be crafted such that none of the outputs of the recipe are voided.

![image](https://user-images.githubusercontent.com/58698520/152629637-a3f3c12e-c9ad-4a3d-b917-b1d95ba2da45.png)

**Comment by Sefiraat** [comment]
Thanks, found and fixed. I am shipping this with an experimental crafter update so it'll be a little while until you see this in a live environment. This issue will close itself when it's shipped :)
