### ISSUE TITLE
刷物品bug

### ISSUE THREAD

**Issue by Xiaodon9-3** [Sefiraat/Networks#49]
Hello, the memory card in the network can be stacked by transportation, so that any item can be copied. Please hurry to repair!

**Comment by Sefiraat** [comment]
This is a known bug in cargo that I cannot directly control. A fix is in the works but, in the mean time, I know there is a Chinese fork with a fix already in place that may be of use - another comment may be added after this with further info regarding that.

谢谢,
Sefi~
