### ISSUE TITLE
[Suggestion] Priority in the network

### ISSUE THREAD

**Issue by mio9** [Sefiraat/Networks#59]
In Applied Energetics and Refined Storage, all inventory facing interfaces (correspond to network monitors and network grabber here in the addon) can be assigned with a priority number where higher priority interfaces will be utilized first. This will allow the setup where network shells to be used first, and then fallback to storage cells for more efficient storage

**Comment by Sefiraat** [comment]
Priority is on the todo-list and will happen when time allows, that being said there is an inbuilt that shells/barrels (anything designated ‘deep’ storage will always fill first and Cells last. The reverse is true when withdrawing. I’ll close this for now as this is on my todo list :). Thanks for the suggestion though :D
