### ISSUE TITLE
Allow more filter slots in Network Pusher

### ISSUE THREAD

**Issue by mio9** [Sefiraat/Networks#62]
The addon has been running smoothly and replaced most of the cargo network for promising performance in comparison. However, there is some use cases that network still falls short and we still must adapt the cargo networks.

The 2 filters in network pushers are not enough for the smeltery, where recipes with 6 different metals exists.
![image](https://user-images.githubusercontent.com/11581624/161816586-c53e4d57-3c02-45c3-8de4-2255fbb63af5.png)

**Comment by Sefiraat** [comment]
Use 3 pushers :) This limit wont be increased without a very good reason :)

**Comment by mio9** [comment]
[slight suggestion] will there be a chance for a tier-like upgrade like the memory wipers? 🤔
