### ISSUE TITLE
Memory Shell stopped functioning

### ISSUE THREAD

**Issue by mio9** [Sefiraat/Networks#63]
![image](https://user-images.githubusercontent.com/11581624/161933430-1523848c-830e-4c8a-977b-9ba8a45d5507.png)

Presumably the item will be stored into the disk, but it stuck at the input instead, and there is no output produced from a card with items present before the shell breaks

**Comment by Sefiraat** [comment]
As at build 34, Network Memory Shells have been disabled and replaced with a far better and more stable alternative. 
This post https://discord.com/channels/809178621424041997/809186242746253363/958408651519959050 (https://discord.gg/SqD3gg5SAU invite if required) may be helpful to you.
