### ISSUE TITLE
Various Issues with the Network Pusher

### ISSUE THREAD

**Issue by marvjosh1** [Sefiraat/Networks#64]
https://www.youtube.com/watch?v=ayp6i65DhIU (0:00 - 1:30)

Not sure what exactly was all going on, but heres a try to summarize:

1. The Network Pusher doesn't recognize the Dust Fabricator or other pushers next to itself
2. It drops all its items inside when broken, and also drops an input node
3. When placed back, it recognizes a non-existing input node

**Comment by Sefiraat** [comment]
This looks like you have some funky BlockStorage data on this and other blocks? Was there a recent crash when you swapped from Cargo to Networks or did you use an odd tool to remove the cargo nodes that perhaps didn't remove the BlockStorage data correctly?
When you broke it and it dropped the Cargo node that's what it thought was there and has then cleared which then allowed the Network block to function correctly but as it uses BlockStorage to determine the blocks around it, it can see the ghost block beside it. 

You will need to go through are clear the ghost blocks and things should be ok from there, though how it happened in interesting. Any more triage information would be great

**Comment by marvjosh1** [comment]
Yeah there was a recent crash, so that might be possible. I was also trying to find the pusher again and it seems the ghost blocks already removed themselves. The player said they removed the nodes with a fluffy wrench.

**Comment by Sefiraat** [comment]
I think the fluffy wrench is solid so it may well be the crash, though it's tricky to work out. Either way it is the ghost blocks causing this and removing them in this video seemed to resolve it so I'll close this for now. Please reopen or open a new one if you find anything more or different.
