### ISSUE TITLE
可以刷物品，希望绑定NBT

### ISSUE THREAD

**Issue by Wooxin** [Sefiraat/Networks#71]
物品改名（改为任意粘液科技物品名）后先放入量子储存绑定，然后输出的，接着放入原本物品绑定，接着再次放入改名的物品，就可以刷物品

**Comment by ybw0014** [comment]
请在此处使用英文汇报，谢谢。
如需反馈汉化版Networks相关问题，请前往此处：https://github.com/SlimefunGuguProject/Networks/issues
