### ISSUE TITLE
Network Vanilla grabber and Vanilla pusher working on locked chests.

### ISSUE THREAD

**Issue by TheRealEzCoins** [Sefiraat/Networks#85]
If you put a Vanilla grabber next to a chestshop or any type of locked chest it'll grab the items out of it.

Plugins;
- ChestShop
- BlockLocker
- Networks

[Video](https://youtu.be/phB0V2T7wFg)

**Comment by Sefiraat** [comment]
This uses slimefun’s default protection to check if the block can be interacted with, if the locking plugins aren’t supported within Slimefun then I’m not sure I can do much here. Can I assume the behaviour is the same with cargo nodes?

**Comment by Sefiraat** [comment]
Never mind, found the cause I think. On it!
