### ISSUE TITLE
[Feature] Greedy network monitors

### ISSUE THREAD

**Issue by Explosivecoin** [Sefiraat/Networks#95]
# Suggestion
Network monitors should be able to be marked as "Greedy". If the item associated with the deep storage it is connected to cannot fit into the quantum storage/infinity barrel, Then it should not enter the network.

# Use case
Stockpiling more than a single stack of an item without flooding the non-deep storage. (and without using cargo to direct insert into the deep storage)

# Alternatives

## Deep before Greedy
Networks could push into deep storage before greedy blocks. If a user has both deep storage and a greedy block for the same item, they probably want for the deep storage to fill before the greedy block.

## Only deep
If there is a deep storage on the network for an item, then that item cannot be inserted into cells

**Comment by Sefiraat** [comment]
Thanks for the suggestion but  this isn't something that will be added at the moment :)
