### ISSUE TITLE
[Suggestion] Grids bypass greedy blocks on insert

### ISSUE THREAD

**Issue by Explosivecoin** [Sefiraat/Networks#96]
# Suggestion
Allow items inserted from the grid to bypass the greedy block if it is full and insert into the network.

# Reason
During crafting it is a pain when extracting extra items to then not be able to reinsert extra items into the network.

**Comment by Sefiraat** [comment]
This would unfortunately break the primary functionality of greedy blocks themselves if items can go else where in the system (given all item insertions and withdrawls use the same code, and cant not do so). Sorry :(
